---
title: "Livelihoods & Economies dashboard data"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/ne-prep/src/templates/ohi_hdr.html'
  pdf_document:
    toc: true
---

Creating data layers for use in the data dashboard

```{r setup, include=FALSE, warning = F, message = F}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)

library(stringr)
library(tidyverse)
```

```{r}
noep <- read_csv("data/clean_noep_data.csv")

### jobs data ###

# grab MA regions and sum jobs per region
ma <- noep %>%
  filter(rgn_id %in% c(7, 8)) %>%
  group_by(rgn_name, rgn_id, Year, Sector) %>%
  mutate(Employment = sum(Employment, na.rm = T),
         Wages      = sum(Wages, na.rm = T),
         GDP        = sum(GDP, na.rm = T)) %>% #this will turn true NAs to 0, we need to swap this back
  select(Year, rgn_id, rgn_name, Employment, Wages, GDP, Sector) %>%
  distinct() %>%
  mutate(Employment = ifelse(Employment == 0, NA, Employment),
         Wages      = ifelse(Wages      == 0, NA, Wages),
         GDP        = ifelse(GDP        == 0, NA, GDP))

noep_fix <- noep %>%
  filter(!rgn_id %in% c(7, 8),
         str_detect(County, "All"),
         rgn_name != "Massachusetts") %>%
  select(Year, rgn_id, rgn_name, Employment, Wages, GDP, Sector) %>%
  bind_rows(ma)
```

Save in the `data` folder

```{r}
#employment by sector
noep_fix %>%
  select(Year, rgn_id, rgn_name, Employment, Sector) %>%
  write.csv("data/jobs_sector.csv")

#wages by sector
noep_fix %>%
  select(Year, rgn_id, rgn_name, Wages, Sector) %>%
  write.csv("data/wages_sector.csv")

#gdp by sector
noep_fix %>%
  select(Year, rgn_id, rgn_name, GDP, Sector) %>%
  write.csv("data/gdp_sector.csv")
```

